### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: Bad request

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mauro-g/snuck#7]
```
Below is my System Information:
OS: Win XP (32 bit)
IDE: Eclipse Platform
Java: 1.7.0_21
WebDriver: 2.31.0 (32 bit)
Firwfox version: 20.0.1
-----------------------------
During run my demo program against Web driver I got below issue:

Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: Bad 
request

Command duration or timeout: 2.37 seconds
Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:53:56'
System info: os.name: 'Windows XP', os.arch: 'x86', os.version: '5.1', 
java.version: '1.7.0_21'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:187)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:190)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:183)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:179)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:92)
    at DemoFunction.main(DemoFunction.java:8)
=============================
Below is Code:(I have already attached all required jre files against WebDriver 
over Eclipse IDE)

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class DemoFunction {

public static void main(String[] args) {
 WebDriver driver = new FirefoxDriver();
 driver.get("http://google.co.in");
 System.out.println("Step1: Title of the Current Page: " + driver.getTitle());  
 System.out.println("Step2: Current URL of the Page: " + driver.getCurrentUrl());
}
}
=============================

Please help me in this concern, I am trying to figure it out but yet I get no 
success.
Please help me in this,
Any help against this is appreciated. 

Looking for your response ASAP.

------------
Regards 
Neeraj
```

Original issue reported on code.google.com by `niraj06....@gmail.com` on 29 Apr 2013 at 11:24

**Comment by Sumonadx** [comment]
Hi , I am also getting exactly the same issue. Can anyone help??
